server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    # 在C:\Windows\System32\drivers\etc路径下添加 127.0.0.1 myzuul.com
    # myzuul.com替代localhost ，url为： http://myzuul.com:9527/
    hostname: myzuul.com
    instance-id: gateway-9527.com
    prefer-ip-address: true
 
 
zuul: 
  #ignored-services: microservicecloud-dept
  prefix: /atguigu
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservicecloud-dept
    # 访问路径：http://myzuul.com:9527/atguigu/mydept/dept/get/111
    mydept.path: /mydept/**
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

